@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/Acme-Has-Tiny/project>
	deps:test-requirement            [ deps:on "Test::Fatal"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Types::Standard"^^deps:CpanId ].

